apiVersion: v1
kind: Namespace
metadata:
  name: tc-microservice-user

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: tc-microservice-user
type: Opaque
data:
  MYSQLDB_USER: cm9vdA==
  MYSQLDB_ROOT_PASSWORD: MTIzNDU2
  MYSQLDB_DATABASE: YXBwX2Ri
  MYSQLDB_DOCKER_PORT: MzMwNg==
  AWS_DB_ACCESS_KEY_ID: cGxhY2Vob2xkZXJwYXJhaWRhd3NiZA==
  AWS_DB_SECRET_ACCESS_KEY: cGxhY2Vob2xkZXJwYXJhc2VuaGFhd3NiZA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: tc-microservice-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: app-container
          image: dovakjr/fase1techchallenge:latest
          ports:
            - containerPort: 3000
          env:
            - name: MYSQLDB_HOST
              value: db-service
            - name: NODE_ENV
              value: PROD
            - name: MYSQLDB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQLDB_USER
            - name: MYSQLDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQLDB_ROOT_PASSWORD
            - name: MYSQLDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQLDB_DATABASE
            - name: MYSQLDB_DOCKER_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQLDB_DOCKER_PORT
          volumeMounts:
            - name: app-volume
              mountPath: /app
          
      volumes:
        - name: app-volume
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: tc-microservice-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pod
  template:
    metadata:
      labels:
        app: db-pod
    spec:
      containers:
        - name: db-container
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQLDB_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQLDB_DATABASE
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: db-volume
          emptyDir: {} #Apenas para desenvolvimento e testes locais.

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: tc-microservice-user
spec:
  selector:
    app: app-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: tc-microservice-user
spec:
  selector:
    app: db-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: tc-microservice-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70